apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: test-aurora-mysql
spec:
  provider: aws
  secretObjects:
    - secretName: mysql
      type: Opaque
      data:
        - key: "DBNAME"
          objectName: "DBNAME"
        - key: "PASSWORD"
          objectName: "PASSWORD"
  parameters:
    objects: |
        - objectName: "test/aurora/mysql"
          objectType: "secretsmanager"
          jmesPath:
            - path: "dbname"
              objectAlias: "DBNAME"
            - path: "password"
              objectAlias: "PASSWORD"